name: Build Kivy APK

on:
  push:
    branches:
      - main

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y openjdk-11-jdk git zip unzip python3-pip python3-setuptools python3-venv
        pip install --upgrade pip
        pip install buildozer kivy pillow cython

    - name: Build APK
      run: buildozer android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: my-kivy-apk
        path: bin/*.apk